version: "3.7"
services:
 backend:
  container_name: deployBackend
  
  restart: always
  build: 
   context: ./backend
   dockerfile: Dockerfile
  environment:
   PORT_BACKEND: 3000
   HOST_DB: cluster0.ubpkb.mongodb.net
   USER_DB: vorellana
   NAME_DB: tripsdb
   PASSWORD_DB: "Trips$$2022"
   
  ports:
   - "3000:3000"