version: "3.7"

services:
 backend:
  container_name: deployBackend
  restart: always
  build: 
   context: ./backend
   dockerfile: Dockerfile
  environment:
   PORT_APP: 3000
   HOST_DB: database
   PORT_DB: 27017
   USER_DB: vorellana
   NAME_DB: tripsdb
   PASSWORD_DB: "Trips2022"
  ports:
   - "3000:3000"
 database:
  container_name: deployDatabase
  restart: always
  build:
   context: ./database
   dockerfile: Dockerfile
  ports:
   - "27017:27017"